[phases.setup]
nixPkgs = ["php", "php.packages.composer", "nodejs"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm ci",
  "npm run build",
  "if [ -f public/build/vite/manifest.json ]; then mv public/build/vite/manifest.json public/build/manifest.json; fi"
]

[start]
cmd = "php artisan migrate --force --seed && php artisan serve --host=0.0.0.0 --port=8000"
